# View raw data: http://localhost:8080/api/rawdata
# Start command: docker-compose up -d --scale whoami=2

version: '3'

services:
  reverse-proxy:
    # 官方的 Traefik 2.0 Docker 镜像
    image: traefik:v2.0
    # 开启 web UI 并且告诉 Traefik 监听 Docker
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge=true"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=alidns"
      - "--certificatesresolvers.mydnschallenge.acme.email=yuga_sun@163.com"
      - "--certificatesresolvers.mydnschallenge.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"
    environment:
      - "ALICLOUD_ACCESS_KEY=HQGRrCCEVVXr6FAa"
      - "ALICLOUD_SECRET_KEY=QP3LsgbW1xAXTGLAS4Xczr7IuCql1g"
    ports:
      # HTTP 端口
      - "80:80"
      # HTTPs 端口
      - "443:443"
      # Web UI 端口(通过 --api.insecure=true 启用)
      - "8080:8080"
    volumes:
      - "/Users/yugasun/Desktop/develop/k3s/letsencrypt:/letsencrypt"
      # 这样 Traefik 可以监听 Docker 事件
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    # 一个通过 API 暴露其 IP 地址的容器
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`k3s.yugasun.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=mydnschallenge"
